apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: goland-expedition-pr
  generateName: goland-expedition-pr-
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: goland-expedition-git
  params:
    - name: imageUrl
      value: "marianferenc/goland-expedition"
    - name: imageTag
      value: "latest"
  serviceAccount: pipeline-account