apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  - port: {{ .Values.service.externalPortGRPC }}
    targetPort: {{ .Values.service.internalPortGRPC }}
    protocol: TCP
    name: {{ .Values.service.name }}-grpc
  selector:
    app: {{ .Values.service.name }}
