sudo: required
language: go

branches:
  only:
  - master

services:
- docker
env:
  global:
  - DOCKER_REPO=marianferenc/goland_expedition:latest
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t $DOCKER_REPO .
deploy:
  provider: script
  script: docker push $DOCKER_REPO
