sudo: required
language: go

branches:
  only:
  - master

services:
- docker
env:
  global:
  - DOCKER_REPO=marianferenc/goland_expedition:latest
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t $DOCKER_REPO .
deploy:
  provider: script
  script: docker push $DOCKER_REPO
cache:
  directories:
  # We cache the SDK so we don't have to download it again on subsequent builds.
  - $HOME/google-cloud-sdk

services:
- docker

env:
  global:
  # Do not prompt for user input when using any SDK methods.
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

script: echo "This should be running tests for continuous integration"

# Deploy  to Google Kubernetes Engine
after_success:
- if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then ./deploy_to_k8s.sh; fi
