sudo: required
language: go

branches:
  only:
  - master
services:
- docker
env:
  global:
  - DOCKER_REPO=marianferenc/goland_expedition:latest
  - HELM_URL=https://storage.googleapis.com/kubernetes-helm
  - HELM_TGZ=helm-v2.4.1-linux-amd64.tar.gz
  - YAMLLINT_VERSION=1.8.1
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - GCLOUD_PROJECT=atvi2-react
before_install:
- openssl aes-256-cbc -K $encrypted_4e3e4fdb1ecb_key -iv $encrypted_4e3e4fdb1ecb_iv -in atvi2-react-ae8746f5e496.json.enc -out atvi2-react-ae8746f5e496.json -d
install:
- wget -q ${HELM_URL}/${HELM_TGZ}
- tar xzfv ${HELM_TGZ}
- PATH=`pwd`/linux-amd64/:$PATH
- helm init --client-only
- sudo pip install yamllint=="${YAMLLINT_VERSION}"
- curl https://sdk.cloud.google.com | bash > /dev/null
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud components install kubectl
- gcloud auth activate-service-account --key-file=atvi2-react-ae8746f5e496.json
- gcloud container clusters get-credentials standard-cluster-1 --zone us-central1-a
  --project atvi2-react
jobs:
  include:
  - stage: push docker image to dockerhub
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_REPO .
    - docker push $DOCKER_REPO
  - stage: push docker image to dockerhub
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_REPO .
    - docker push $DOCKER_REPO
  - stage: k8s
    script:
    - kubectl version
    - helm version
