apiVersion: skaffold/v1beta13
kind: Config
metadata:
  name: goland-expedition
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: marianferenc/golang_expedition
      context: .
deploy:
  helm:
    releases:
      - name: goland-expedition
        chartPath: charts/goland_expedition