// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Detection struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XCoordinate          string   `protobuf:"bytes,2,opt,name=x_coordinate,json=xCoordinate,proto3" json:"x_coordinate,omitempty"`
	YCoordinate          string   `protobuf:"bytes,3,opt,name=y_coordinate,json=yCoordinate,proto3" json:"y_coordinate,omitempty"`
	BodyPart             string   `protobuf:"bytes,4,opt,name=bodyPart,proto3" json:"bodyPart,omitempty"`
	Timestamp            string   `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Detection) Reset()         { *m = Detection{} }
func (m *Detection) String() string { return proto.CompactTextString(m) }
func (*Detection) ProtoMessage()    {}
func (*Detection) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Detection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Detection.Unmarshal(m, b)
}
func (m *Detection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Detection.Marshal(b, m, deterministic)
}
func (m *Detection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Detection.Merge(m, src)
}
func (m *Detection) XXX_Size() int {
	return xxx_messageInfo_Detection.Size(m)
}
func (m *Detection) XXX_DiscardUnknown() {
	xxx_messageInfo_Detection.DiscardUnknown(m)
}

var xxx_messageInfo_Detection proto.InternalMessageInfo

func (m *Detection) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Detection) GetXCoordinate() string {
	if m != nil {
		return m.XCoordinate
	}
	return ""
}

func (m *Detection) GetYCoordinate() string {
	if m != nil {
		return m.YCoordinate
	}
	return ""
}

func (m *Detection) GetBodyPart() string {
	if m != nil {
		return m.BodyPart
	}
	return ""
}

func (m *Detection) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type DetectionRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetectionRequest) Reset()         { *m = DetectionRequest{} }
func (m *DetectionRequest) String() string { return proto.CompactTextString(m) }
func (*DetectionRequest) ProtoMessage()    {}
func (*DetectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *DetectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectionRequest.Unmarshal(m, b)
}
func (m *DetectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectionRequest.Marshal(b, m, deterministic)
}
func (m *DetectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectionRequest.Merge(m, src)
}
func (m *DetectionRequest) XXX_Size() int {
	return xxx_messageInfo_DetectionRequest.Size(m)
}
func (m *DetectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetectionRequest proto.InternalMessageInfo

func (m *DetectionRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DetectionResponse struct {
	Detection            *Detection `protobuf:"bytes,1,opt,name=detection,proto3" json:"detection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DetectionResponse) Reset()         { *m = DetectionResponse{} }
func (m *DetectionResponse) String() string { return proto.CompactTextString(m) }
func (*DetectionResponse) ProtoMessage()    {}
func (*DetectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *DetectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectionResponse.Unmarshal(m, b)
}
func (m *DetectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectionResponse.Marshal(b, m, deterministic)
}
func (m *DetectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectionResponse.Merge(m, src)
}
func (m *DetectionResponse) XXX_Size() int {
	return xxx_messageInfo_DetectionResponse.Size(m)
}
func (m *DetectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetectionResponse proto.InternalMessageInfo

func (m *DetectionResponse) GetDetection() *Detection {
	if m != nil {
		return m.Detection
	}
	return nil
}

func init() {
	proto.RegisterType((*Detection)(nil), "proto.Detection")
	proto.RegisterType((*DetectionRequest)(nil), "proto.DetectionRequest")
	proto.RegisterType((*DetectionResponse)(nil), "proto.DetectionResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x95, 0x84, 0x22, 0x7c, 0xa5, 0xa8, 0x78, 0xc1, 0xaa, 0x18, 0xc0, 0x13, 0x53, 0x86,
	0xb2, 0xb0, 0xa7, 0x12, 0x62, 0x43, 0x91, 0x98, 0x51, 0x1a, 0xdf, 0xe0, 0x21, 0x71, 0xb0, 0x0f,
	0x94, 0x3c, 0x0b, 0x2f, 0x8b, 0x62, 0x0b, 0xc7, 0x52, 0x26, 0xcb, 0xff, 0xf7, 0x9d, 0xee, 0x3f,
	0xd8, 0x39, 0xb4, 0x3f, 0xba, 0xc5, 0x72, 0xb0, 0x86, 0x0c, 0xdf, 0xf8, 0x47, 0xfe, 0x66, 0xc0,
	0x4e, 0x48, 0xd8, 0x92, 0x36, 0x3d, 0xbf, 0x81, 0x5c, 0x2b, 0x91, 0x3d, 0x64, 0x4f, 0xac, 0xce,
	0xb5, 0xe2, 0x8f, 0x70, 0x3d, 0x7e, 0xb6, 0xc6, 0x58, 0xa5, 0xfb, 0x86, 0x50, 0xe4, 0x9e, 0x6c,
	0xc7, 0x2a, 0x46, 0xb3, 0x32, 0xa5, 0x4a, 0x11, 0x94, 0x29, 0x51, 0x0e, 0x70, 0x75, 0x36, 0x6a,
	0x7a, 0x6f, 0x2c, 0x89, 0x0b, 0x8f, 0xe3, 0x9f, 0xdf, 0x03, 0x23, 0xdd, 0xa1, 0xa3, 0xa6, 0x1b,
	0xc4, 0xc6, 0xc3, 0x25, 0x90, 0x12, 0xf6, 0xb1, 0x5c, 0x8d, 0x5f, 0xdf, 0xe8, 0x28, 0xe9, 0x58,
	0xcc, 0x1d, 0x65, 0x05, 0xb7, 0x89, 0xe3, 0x06, 0xd3, 0x3b, 0xe4, 0x25, 0x30, 0xf5, 0x1f, 0x7a,
	0x77, 0x7b, 0xdc, 0x87, 0xc3, 0xcb, 0x45, 0x5e, 0x94, 0xe3, 0x1b, 0xec, 0x62, 0x5e, 0xd5, 0x1f,
	0x27, 0xfe, 0x02, 0xc5, 0x2b, 0x12, 0xbf, 0x5b, 0x0d, 0x85, 0x16, 0x07, 0xb1, 0x06, 0x61, 0xf5,
	0xf9, 0xd2, 0x83, 0xe7, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x28, 0x87, 0x19, 0x01, 0x70, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DetectionCRUDClient is the client API for DetectionCRUD service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DetectionCRUDClient interface {
	Get(ctx context.Context, in *DetectionRequest, opts ...grpc.CallOption) (*DetectionResponse, error)
}

type detectionCRUDClient struct {
	cc *grpc.ClientConn
}

func NewDetectionCRUDClient(cc *grpc.ClientConn) DetectionCRUDClient {
	return &detectionCRUDClient{cc}
}

func (c *detectionCRUDClient) Get(ctx context.Context, in *DetectionRequest, opts ...grpc.CallOption) (*DetectionResponse, error) {
	out := new(DetectionResponse)
	err := c.cc.Invoke(ctx, "/proto.DetectionCRUD/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DetectionCRUDServer is the server API for DetectionCRUD service.
type DetectionCRUDServer interface {
	Get(context.Context, *DetectionRequest) (*DetectionResponse, error)
}

// UnimplementedDetectionCRUDServer can be embedded to have forward compatible implementations.
type UnimplementedDetectionCRUDServer struct {
}

func (*UnimplementedDetectionCRUDServer) Get(ctx context.Context, req *DetectionRequest) (*DetectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterDetectionCRUDServer(s *grpc.Server, srv DetectionCRUDServer) {
	s.RegisterService(&_DetectionCRUD_serviceDesc, srv)
}

func _DetectionCRUD_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectionCRUDServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DetectionCRUD/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectionCRUDServer).Get(ctx, req.(*DetectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DetectionCRUD_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DetectionCRUD",
	HandlerType: (*DetectionCRUDServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _DetectionCRUD_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
